version: "3"
services:
  view:
    build: ./view
    container_name: "tracking-parking-view"
    volumes:
      - ./view:/app
    command: "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - NEXT_PUBLIC_MONGODB_URI=MONGODB_URI=mongodb://root:password@mongo:27017/test?authSource=admin
      - NEXT_PUBLIC_MONGODB_DB=tracking_parking
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-db:
