version: "3"
services:
  cloudflare:
    image: "cloudflare/cloudflared:latest"
    container_name: "nutfes-trapa-web"
    volumes: ["./web/prod:/home/nonroot/.cloudflared"]
    command: tunnel run

  view:
    build: ./view
    container_name: "tracking-parking-view"
    volumes:
      - ./view:/app
    command: "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      NEXT_PUBLIC_MONGODB_URI: mongodb://root:password@mongo:27017/test?authSource=admin
      NEXT_PUBLIC_MONGODB_DB: tracking_parking
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

volumes:
  mongo-db:
