version: "3"
services:
  view:
    build: ./view
    container_name: "tracking-parking-view"
    volumes:
      - ./view:/app
    command: "npm run start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
      - ./mongo:/data/configdb
