import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>TrackingParking</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main>
        <div>
          <p className='text-2xl text-slate-800'>Tracking Parking</p>
        </div>
      </main>
    </>
  )
}
